# Feature Engineering
This notebook generate features according to the prepared dataset. The main operations performed are:
- Computing for demographic percentages
- Aggregating income variables
- Aggregating inflow population by income levels

In [18]:
import pandas as pd
import numpy as np

In [19]:
df = pd.read_csv('training_data.csv')

In [20]:
df.head(10)

,Unnamed: 0,pop,white,hh,medhinc,mhval,mrent,ohu,rhu,total_bd,...,typology,year,typ_cat,rail,total_li,pctch_real_mhval_sl,per_ch_rent_sl,lostli,more_ind_inc,pctch_ind_inc
0,0,3726.0,1475.0,2190.0,57404.958678,245123.966942,1034.710744,689.0,1501.0,775.0,...,NaN,2023,NaN,0.0,732.0,-0.047692,0.183880,-398.0,1,0.118908
1,1,7588.0,1883.0,3038.0,41023.966942,197603.305785,1101.652893,823.0,2215.0,684.0,...,NaN,2023,NaN,0.0,701.0,0.262641,0.076885,-582.0,1,0.210674
2,2,2609.0,987.0,1130.0,45552.892562,191652.892562,1067.768595,270.0,860.0,656.0,...,NaN,2023,NaN,1.0,295.0,0.199330,0.097398,-216.0,1,0.257321
3,3,6311.0,3558.0,3185.0,54438.842975,252066.115702,1038.842975,859.0,2326.0,1585.0,...,NaN,2023,NaN,1.0,902.0,0.450323,0.064388,-447.0,1,0.062125
4,4,4282.0,3349.0,2058.0,40509.917355,189586.776860,1031.404959,513.0,1545.0,999.0,...,NaN,2023,NaN,0.0,751.0,-0.132326,0.021193,-54.0,1,0.378890
5,5,3519.0,2298.0,2379.0,39876.033058,162479.338843,971.900826,341.0,2038.0,1157.0,...,NaN,2023,NaN,0.0,849.0,-0.486637,0.007151,-384.0,1,0.118400
6,6,3329.0,2171.0,1637.0,50716.528926,233223.140496,1083.471074,469.0,1168.0,770.0,...,NaN,2023,NaN,0.0,544.0,0.046313,0.093311,-160.0,1,0.169920
7,7,2844.0,1806.0,1477.0,18119.008264,388842.975207,927.272727,177.0,1300.0,350.0,...,NaN,2023,NaN,1.0,873.0,0.125124,0.343874,271.0,0,-0.208914
8,8,6708.0,3804.0,3066.0,59438.016529,210330.578512,1054.545455,1094.0,1972.0,1843.0,...,NaN,2023,NaN,1.0,666.0,-0.060605,0.061979,-435.0,1,0.199578
9,9,3573.0,1431.0,1652.0,61328.925620,285454.545455,1105.785124,820.0,832.0,1047.0,...,NaN,2023,NaN,1.0,392.0,0.379674,0.065304,-64.0,1,0.229999

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3815 entries, 0 to 3814
Data columns (total 84 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           3815 non-null   int64
 1   pop                  3815 non-null   float64
 2   white                3815 non-null   float64
 3   hh                   3815 non-null   float64
 4   medhinc              3815 non-null   float64
 5   mhval                3815 non-null   float64
 6   mrent                3815 non-null   float64
 7   ohu                  3815 non-null   float64
 8   rhu                  3815 non-null   float64
 9   total_bd             3815 non-null   float64
 10  total_md             3815 non-null   float64
 11  total_pd             3815 non-null   float64
 12  total_phd            3815 non-null   float64
 13  tot_units_built      3815 non-null   float64
 14  units_40_49          3815 non-null   float64
 15  units_39_earlier     3815 non-null   float64
 16  mov_wc_w_income      3815 non-null   float64
 17  mov_wc_9000          3815 non-null   float64
 18  mov_wc_15000         3815 non-null   float64
 19  mov_wc_25000         3815 non-null   float64
 20  mov_wc_35000         3815 non-null   float64
 21  mov_wc_50000         3815 non-null   float64
 22  mov_wc_65000         3815 non-null   float64
 23  mov_wc_75000         3815 non-null   float64
 24  mov_wc_76000_more    3815 non-null   float64
 25  mov_oc_w_income      3815 non-null   float64
 26  mov_oc_9000          3815 non-null   float64
 27  mov_oc_15000         3815 non-null   float64
 28  mov_oc_25000         3815 non-null   float64
 29  mov_oc_35000         3815 non-null   float64
 30  mov_oc_50000         3815 non-null   float64
 31  mov_oc_65000         3815 non-null   float64
 32  mov_oc_75000         3815 non-null   float64
 33  mov_oc_76000_more    3815 non-null   float64
 34  mov_os_w_income      3815 non-null   float64
 35  mov_os_9000          3815 non-null   float64
 36  mov_os_15000         3815 non-null   float64
 37  mov_os_25000         3815 non-null   float64
 38  mov_os_35000         3815 non-null   float64
 39  mov_os_50000         3815 non-null   float64
 40  mov_os_65000         3815 non-null   float64
 41  mov_os_75000         3815 non-null   float64
 42  mov_os_76000_more    3815 non-null   float64
 43  mov_fa_w_income      3815 non-null   float64
 44  mov_fa_9000          3815 non-null   float64
 45  mov_fa_15000         3815 non-null   float64
 46  mov_fa_25000         3815 non-null   float64
 47  mov_fa_35000         3815 non-null   float64
 48  mov_fa_50000         3815 non-null   float64
 49  mov_fa_65000         3815 non-null   float64
 50  state                3815 non-null   int64
 51  county               3815 non-null   int64
 52  tract                3815 non-null   int64
 53  mov_fa_75000         3815 non-null   float64
 54  mov_fa_76000_more    3815 non-null   float64
 55  iinc                 3815 non-null   float64
 56  hinc                 3815 non-null   float64
 57  I_10000              3815 non-null   float64
 58  I_15000              3815 non-null   float64
 59  I_20000              3815 non-null   float64
 60  I_25000              3815 non-null   float64
 61  I_30000              3815 non-null   float64
 62  I_35000              3815 non-null   float64
 63  I_40000              3815 non-null   float64
 64  I_45000              3815 non-null   float64
 65  I_50000              3815 non-null   float64
 66  I_60000              3815 non-null   float64
 67  I_75000              3815 non-null   float64
 68  I_100000             3815 non-null   float64
 69  I_125000             3815 non-null   float64
 70  I_150000             3815 non-null   float64
 71  I_200000             3815 non-null   float64
 72  I_201000             3815 non-null   float64
 73  FIPS                 3815 non-null   int64
 74  typology             1909 non-null   float64
 75  year                 3815 non-null   int64
 76  typ_cat              1909 non-null   object
 77  rail                 3815 non-null   float64
 78  total_li             3815 non-null   float64
 79  pctch_real_mhval_sl  3815 non-null   float64
 80  per_ch_rent_sl       3815 non-null   float64
 81  lostli               3815 non-null   float64
 82  more_ind_inc         3815 non-null   int64
 83  pctch_ind_inc        3815 non-null   float64
dtypes: float64(76), int64(7), object(1)
memory usage: 2.4+ MB

## Dealing with Skewness

In [5]:
# first, drop the first column (due to file import format)
df.drop(columns=['Unnamed: 0'], inplace=True)

In [6]:
# create log-transformations to handle skewness
for col in ['medhinc', 'mhval', 'mrent', 'iinc']:
    # Avoid log(0) by replacing zeros with NaN first.
    df[f'log_{col}'] = np.log(df[col])

## Compute Proportion/Ratio Features

In [7]:
# generate new features based inflow migration by income level
mov_low_inc = []
mov_med_inc = []
mov_high_inc = []

low = ['9000', '15000', '25000']
med = ['35000', '50000', '65000']
high = ['75000', '76000_more']

direction = ['wc', 'oc', 'os', 'fa'] # within county, from other county, from other state, from foreign countries

for d in direction:
    for l in low:
        mov_low_inc.append(f'mov_{d}_{l}')
    for m in med:
        mov_med_inc.append(f'mov_{d}_{m}')
    for h in high:
        mov_high_inc.append(f'mov_{d}_{h}')

print(mov_low_inc)
print(mov_med_inc)
print(mov_high_inc)

['mov_wc_9000', 'mov_wc_15000', 'mov_wc_25000', 'mov_oc_9000', 'mov_oc_15000', 'mov_oc_25000', 'mov_os_9000', 'mov_os_15000', 'mov_os_25000', 'mov_fa_9000', 'mov_fa_15000', 'mov_fa_25000']
['mov_wc_35000', 'mov_wc_50000', 'mov_wc_65000', 'mov_oc_35000', 'mov_oc_50000', 'mov_oc_65000', 'mov_os_35000', 'mov_os_50000', 'mov_os_65000', 'mov_fa_35000', 'mov_fa_50000', 'mov_fa_65000']
['mov_wc_75000', 'mov_wc_76000_more', 'mov_oc_75000', 'mov_oc_76000_more', 'mov_os_75000', 'mov_os_76000_more', 'mov_fa_75000', 'mov_fa_76000_more']

In [8]:
# create new features indicating inflow migration by income level
df['mov_low_inc'] = df[mov_low_inc].sum(axis=1)
df['mov_med_inc'] = df[mov_med_inc].sum(axis=1)
df['mov_high_inc'] = df[mov_high_inc].sum(axis=1)

In [9]:
# calculate price to rent ratio
df['price_rent_ratio'] = df['mhval'] / df['mrent']

In [10]:
# create ratio/proportion features
# white population
df['white_prop'] = df['white'] / df['pop']

# proportion of owner-occupied housing units and renter-occupied housing units
df['ohu_prop'] = df['ohu'] / df['hh']
df['rhu_prop'] = df['rhu'] / df['hh']

# proportion of old buildings
df['pro_old_build'] = (df['units_40_49'] + df['units_39_earlier']) / df['tot_units_built']

# proportion of lost low income households
df['prop_lostli'] = df['lostli'] / df['hh']

# proportion of inflow individuals by income level
df['prop_mov_low_inc'] = df['mov_low_inc'] / df['pop']
df['prop_mov_med_inc'] = df['mov_med_inc'] / df['pop']
df['prop_mov_high_inc'] = df['mov_high_inc'] / df['pop']

# proportion of inflow individuals by income level (non-aggregated). This is important for our model
prop_mv_vars = []
for i in ['9000', '15000', '25000', '35000', '50000', '65000', '75000', '76000_more']:
    for j in ['wc', 'oc', 'os', 'fa']:
        prop_mv_vars.append(f'prop_mov_{j}_{i}')
        df[f'prop_mov_{j}_{i}'] = df[f'mov_{j}_{i}'] / df['pop']

tot_mv_vars = []
for i in ['wc', 'oc', 'os', 'fa']:
    tot_mv_vars.append(f'mov_{i}_w_income')
    df[f'prop_mov_{i}_w_income'] = df[f'mov_{i}_w_income'] / df['pop']

# proportion of households by income level
inc_vars = []
prop_inc_vars = []
for i in ['10000', '15000', '20000', '25000', '30000', '35000', '40000', '45000', '50000', '60000', '75000', '100000', '125000', '150000', '200000', '201000']:
    inc_vars.append(f'I_{i}')
    prop_inc_vars.append(f'prop_hhinc_{i}')
    df[f'prop_hhinc_{i}'] = df[f'I_{i}'] / df['hinc'] # divided by total number of households that reported income in the past 12 months


# proportion of individuals by education level
edu_vars = ['total_bd', 'total_md', 'total_pd', 'total_phd']
df['prop_bd'] = df['total_bd'] / df['pop']
df['prop_grad'] = (df['total_md'] + df['total_pd'] + df['total_phd']) / df['pop']

In [11]:
missing_info = df.isnull().sum()
print("col with null val:")
print(missing_info[missing_info > 0])

col with null val:
typology    1906
typ_cat     1906
dtype: int64

In [12]:
# take a look at the new features
for col in df.columns:
    print(col)

pop
white
hh
medhinc
mhval
mrent
ohu
rhu
total_bd
total_md
total_pd
total_phd
tot_units_built
units_40_49
units_39_earlier
mov_wc_w_income
mov_wc_9000
mov_wc_15000
mov_wc_25000
mov_wc_35000
mov_wc_50000
mov_wc_65000
mov_wc_75000
mov_wc_76000_more
mov_oc_w_income
mov_oc_9000
mov_oc_15000
mov_oc_25000
mov_oc_35000
mov_oc_50000
mov_oc_65000
mov_oc_75000
mov_oc_76000_more
mov_os_w_income
mov_os_9000
mov_os_15000
mov_os_25000
mov_os_35000
mov_os_50000
mov_os_65000
mov_os_75000
mov_os_76000_more
mov_fa_w_income
mov_fa_9000
mov_fa_15000
mov_fa_25000
mov_fa_35000
mov_fa_50000
mov_fa_65000
state
county
tract
mov_fa_75000
mov_fa_76000_more
iinc
hinc
I_10000
I_15000
I_20000
I_25000
I_30000
I_35000
I_40000
I_45000
I_50000
I_60000
I_75000
I_100000
I_125000
I_150000
I_200000
I_201000
FIPS
typology
year
typ_cat
rail
total_li
pctch_real_mhval_sl
per_ch_rent_sl
lostli
more_ind_inc
pctch_ind_inc
log_medhinc
log_mhval
log_mrent
log_iinc
mov_low_inc
mov_med_inc
mov_high_inc
price_rent_ratio
white_prop
ohu_prop
rhu_prop
pro_old_build
prop_lostli
prop_mov_low_inc
prop_mov_med_inc
prop_mov_high_inc
prop_mov_wc_9000
prop_mov_oc_9000
prop_mov_os_9000
prop_mov_fa_9000
prop_mov_wc_15000
prop_mov_oc_15000
prop_mov_os_15000
prop_mov_fa_15000
prop_mov_wc_25000
prop_mov_oc_25000
prop_mov_os_25000
prop_mov_fa_25000
prop_mov_wc_35000
prop_mov_oc_35000
prop_mov_os_35000
prop_mov_fa_35000
prop_mov_wc_50000
prop_mov_oc_50000
prop_mov_os_50000
prop_mov_fa_50000
prop_mov_wc_65000
prop_mov_oc_65000
prop_mov_os_65000
prop_mov_fa_65000
prop_mov_wc_75000
prop_mov_oc_75000
prop_mov_os_75000
prop_mov_fa_75000
prop_mov_wc_76000_more
prop_mov_oc_76000_more
prop_mov_os_76000_more
prop_mov_fa_76000_more
prop_mov_wc_w_income
prop_mov_oc_w_income
prop_mov_os_w_income
prop_mov_fa_w_income
prop_hhinc_10000
prop_hhinc_15000
prop_hhinc_20000
prop_hhinc_25000
prop_hhinc_30000
prop_hhinc_35000
prop_hhinc_40000
prop_hhinc_45000
prop_hhinc_50000
prop_hhinc_60000
prop_hhinc_75000
prop_hhinc_100000
prop_hhinc_125000
prop_hhinc_150000
prop_hhinc_200000
prop_hhinc_201000
prop_bd
prop_grad

In [13]:
# store a full version of the data for possible future use
df.to_csv('training_data_extended.csv', index=False)

In [14]:
# generate a smaller, cleaned version of selected features for model training
# drop variables that were used to create proportion features
df_c = df.copy()
df_c.drop(columns=['units_40_49', 'units_39_earlier'], inplace=True)
df_c.drop(columns=['hinc'], inplace=True)
df_c.drop(columns=inc_vars, inplace=True)
df_c.drop(columns=['mov_low_inc', 'mov_med_inc', 'mov_high_inc'], inplace=True)
df_c.drop(columns=mov_low_inc + mov_med_inc + mov_high_inc, inplace=True)
df_c.drop(columns=['white', 'ohu', 'rhu'], inplace=True)
df_c.drop(columns=edu_vars, inplace=True)
df_c.drop(columns=['mrent', 'mhval', 'iinc', 'medhinc'], inplace=True)
df_c.drop(columns=['tot_units_built'], inplace=True)
df_c.drop(columns= tot_mv_vars, inplace=True)
df_c.drop(columns=['typ_cat', 'typology'], inplace=True)

print(df_c.columns) # inspect the features

Index(['pop', 'hh', 'state', 'county', 'tract', 'FIPS', 'year', 'rail',
       'total_li', 'pctch_real_mhval_sl', 'per_ch_rent_sl', 'lostli',
       'more_ind_inc', 'pctch_ind_inc', 'log_medhinc', 'log_mhval',
       'log_mrent', 'log_iinc', 'price_rent_ratio', 'white_prop', 'ohu_prop',
       'rhu_prop', 'pro_old_build', 'prop_lostli', 'prop_mov_low_inc',
       'prop_mov_med_inc', 'prop_mov_high_inc', 'prop_mov_wc_9000',
       'prop_mov_oc_9000', 'prop_mov_os_9000', 'prop_mov_fa_9000',
       'prop_mov_wc_15000', 'prop_mov_oc_15000', 'prop_mov_os_15000',
       'prop_mov_fa_15000', 'prop_mov_wc_25000', 'prop_mov_oc_25000',
       'prop_mov_os_25000', 'prop_mov_fa_25000', 'prop_mov_wc_35000',
       'prop_mov_oc_35000', 'prop_mov_os_35000', 'prop_mov_fa_35000',
       'prop_mov_wc_50000', 'prop_mov_oc_50000', 'prop_mov_os_50000',
       'prop_mov_fa_50000', 'prop_mov_wc_65000', 'prop_mov_oc_65000',
       'prop_mov_os_65000', 'prop_mov_fa_65000', 'prop_mov_wc_75000',
       'prop_mov_oc_75000', 'prop_mov_os_75000', 'prop_mov_fa_75000',
       'prop_mov_wc_76000_more', 'prop_mov_oc_76000_more',
       'prop_mov_os_76000_more', 'prop_mov_fa_76000_more',
       'prop_mov_wc_w_income', 'prop_mov_oc_w_income', 'prop_mov_os_w_income',
       'prop_mov_fa_w_income', 'prop_hhinc_10000', 'prop_hhinc_15000',
       'prop_hhinc_20000', 'prop_hhinc_25000', 'prop_hhinc_30000',
       'prop_hhinc_35000', 'prop_hhinc_40000', 'prop_hhinc_45000',
       'prop_hhinc_50000', 'prop_hhinc_60000', 'prop_hhinc_75000',
       'prop_hhinc_100000', 'prop_hhinc_125000', 'prop_hhinc_150000',
       'prop_hhinc_200000', 'prop_hhinc_201000', 'prop_bd', 'prop_grad'],
      dtype='object')

In [15]:
df_c[['lostli', 'prop_lostli']].describe()

            lostli  prop_lostli
count  3815.000000  3815.000000
mean    -40.981888    -0.028814
std     101.714511     0.070025
min    -904.000000    -0.587662
25%     -64.000000    -0.046258
50%       0.000000     0.000000
75%       0.000000     0.000000
max     664.000000     0.383495

In [16]:
df_c.to_csv('training_data_features.csv', index=False)